### ISSUE TITLE
Is there any way to enforce signed-headers?

### ISSUE THREAD

**Issue by pmoubed** [1ma/UMAPsr7HmacBundle#4]
Is there any way to enforce signed-headers? how to enforce certain key to be present in signed header keys? e.g. x-date is required to be part of signed header.

**Comment by 1ma** [comment]
Yes, coding [your own Inspector](https://github.com/1ma/Psr7Hmac/issues/10#issuecomment-325571708), defining it as a service and passing it to the [`inspector_id`](https://github.com/1ma/UMAPsr7HmacBundle/issues/5#issuecomment-325568057)  option :slightly_smiling_face:
