### ISSUE TITLE
Is there any documentation for inspector_id? 

### ISSUE THREAD

**Issue by pmoubed** [1ma/UMAPsr7HmacBundle#5]
Is there any documentation for inspector_id and custom inspector?

**Comment by 1ma** [comment]
Sorry, I'm afraid there isn't yet. You can pass a service name to `inspector_id` and the bundle will take care of injecting that inspector into the `Verifier` it uses. Of course, the only requirement is that the service implements the `InspectorInterface`.

The testing suite exerts that feature, you can take a look at:
[Inspector class](https://github.com/1ma/UMAPsr7HmacBundle/blob/185ae60fa55a3ef489a6f58c57d9b8320aefda1d/tests/TestProject/src/AppBundle/Security/CustomInspector.php)
[Service definition](https://github.com/1ma/UMAPsr7HmacBundle/blob/master/tests/TestProject/app/config/config.yml#L15)
[Bundle setup](https://github.com/1ma/UMAPsr7HmacBundle/blob/master/tests/TestProject/app/config/security.yml#L11)
